### ISSUE TITLE
The regex in the paper is missing the opening parenthesis

### ISSUE THREAD

**Issue by Daniel-Mietchen** [weltliteratur/vossanto#1]
In the paper at https://doi.org/10.1093/llc/fqy087 , the regex is given as 

```
\\bthe\\s+([\\w.,'-]+\\s+){1,5}?of\\b)
```
(directly followed by a ```.``` to indicate the end of the sentence but that is not made clear), which misses the opening parenthesis, as per https://github.com/weltliteratur/vossanto/blob/986b7b2b7c014c25162a5fa00b2786dd9257215c/theof/theof.py#L64 .

**Comment by rjoberon** [comment]
Thank you Daniel. We will try to fix that. Independent of that, we will soon publish an open access pre-print that will not suffer from that error.

**Comment by lehkost** [comment]
Yes thanks, this must have happened when converting to the journal format, it's accurate in the preprint we [just published](https://arxiv.org/abs/1902.06428).
